{{- $apiContext := (merge dict . .Values.api) -}}
{{- if (eq .Values.encryption.provider "bcrypt") }}
{{- $secretName := (printf "%s-bcrypt" (include "common.names.fullname" $apiContext) | trunc 63 | trimSuffix "-") }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" $apiContext | quote }}
  labels:
    {{- include "osie.labels" $apiContext | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  bcrypt-password: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "bcrypt-password" "length" 16 "providedValues" (list "encryption.bcrypt.password") "context" $apiContext) }}
{{- end }}
