{{- $keycloakContext := (merge dict . .Values.keycloak) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.dependency.fullname" (dict "chartName" "keycloak" "chartValues" .Values.keycloak "context" $) }}-realm
  namespace: {{ include "common.names.namespace" $keycloakContext | quote }}
  labels:
    {{- include "osie.labels" $keycloakContext | nindent 4 }}
data:
  clients.yml: |
    id: {{ .Values.ui.oauth2.realm }}
    realm: {{ .Values.ui.oauth2.realm }}
    displayName: Osie
    displayNameHtml: <div class="kc-logo-text"><span>Osie</span></div>
    registrationAllowed: true
    registrationEmailAsUsername: true
    accessTokenLifespan: 3600
    accessTokenLifespanForImplicitFlow: 3600
    ssoSessionIdleTimeout: 300
    ssoSessionMaxLifespan: 36000
    enabled: true
    loginTheme: osie
    clients:
      - clientId: {{ .Values.ui.oauth2.clientId | quote}}
        enabled: true
        alwaysDisplayInConsole: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - {{ include "osie.uiUrl" . }}
          - {{ include "osie.uiUrl" . }}/
          - {{ include "osie.uiUrl" . }}/*
        webOrigins:
          - "*"
        notBefore: 0
        bearerOnly: false
        consentRequired: false
        standardFlowEnabled: true
        implicitFlowEnabled: true
        directAccessGrantsEnabled: true
        publicClient: true
        frontchannelLogout: false
        protocol: openid-connect
        attributes:
          access.token.lifespan: '3600'
          login_theme: osie
        fullScopeAllowed: true
        nodeReRegistrationTimeout: -1
        defaultClientScopes:
          - web-origins
          - roles
          - profile
          - email
        optionalClientScopes:
          - address
          - phone
          - offline_access
          - microprofile-jwt
  admins.yml: |
    id: {{ .Values.admin.oauth2.realm }}
    realm: {{ .Values.admin.oauth2.realm }}
    displayName: Osie Admin
    displayNameHtml: <div class="kc-logo-text"><span>Osie Admin</span></div>
    accessTokenLifespan: 3600
    accessTokenLifespanForImplicitFlow: 3600
    registrationEmailAsUsername: true
    ssoSessionIdleTimeout: 300
    ssoSessionMaxLifespan: 36000
    loginTheme: osie
    enabled: true
    clients:
      - clientId: {{ .Values.admin.oauth2.clientId | quote}}
        enabled: true
        alwaysDisplayInConsole: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - {{ include "osie.adminUrl" . }}
          - {{ include "osie.adminUrl" . }}/
          - {{ include "osie.adminUrl" . }}/*
        webOrigins:
          - "*"
        notBefore: 0
        bearerOnly: false
        consentRequired: false
        standardFlowEnabled: true
        implicitFlowEnabled: true
        directAccessGrantsEnabled: true
        publicClient: true
        frontchannelLogout: false
        protocol: openid-connect
        attributes:
          access.token.lifespan: '3600'
        fullScopeAllowed: true
        nodeReRegistrationTimeout: -1
        defaultClientScopes:
          - web-origins
          - roles
          - profile
          - email
        optionalClientScopes:
          - address
          - phone
          - offline_access
          - microprofile-jwt