{{- $adminContext := (merge dict . .Values.admin) -}}
{{- $apiContext := (merge dict . .Values.api) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osie.componentName" $adminContext }}
  labels:
    {{- include "osie.labels" $adminContext | nindent 4 }}
spec:
  replicas: {{ $adminContext.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "osie.selectorLabels" $adminContext | nindent 6 }}
  template:
    metadata:
      {{- with $adminContext.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osie.labels" $adminContext | nindent 8 }}
    spec:
      {{- with $adminContext.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $adminContext.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $adminContext.component }}
          securityContext:
            {{- toYaml $adminContext.securityContext | nindent 12 }}
          image: "{{ $adminContext.image.repository }}:{{ $adminContext.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $adminContext.image.pullPolicy }}
          env:
            - name: OSIE_OAUTH2_CLIENT_ID
              value: {{ $adminContext.oauth2.clientId }}
            - name: OSIE_OAUTH2_ISSUER
              value: {{ include "osie.admin.oauth2IssuerUri" . }}
            - name: OSIE_REDIRECT_URI
              value: {{ include "osie.adminUrl" . }}/
            - name: OSIE_API_URL
              value: {{ include "osie.apiUrl" .}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /osie_admin/
              port: http
          readinessProbe:
            httpGet:
              path: /osie_admin/
              port: http
          resources:
            {{- toYaml $adminContext.resources | nindent 12 }}
      {{- with $adminContext.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $adminContext.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $adminContext.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
