{{- if .Values.global.ingress.enabled }}
{{- $uiContext := (merge dict . .Values.ui) -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "osie.componentName" $uiContext }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "osie.labels" $uiContext | nindent 4 }}
  annotations:
    {{- if .Values.global.ingress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.global.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.global.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{ include "osie.ingressRule" $uiContext | nindent 4}}

  {{- if or (and .Values.global.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.global.ingress.annotations )) .Values.global.ingress.secrets ))  }}
  tls:
  {{- if and .Values.global.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.global.ingress.annotations )) .Values.global.ingress.secrets) }}
    - hosts:
        - {{ include "osie.ingressHostname" $uiContext }}
      secretName: {{ printf "%s-tls" (include "osie.ingressHostname" $uiContext) }}
    {{- end }}
  {{- end }}
{{- end }}
