{{- if .Values.rabbitmq.auth.password -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-rabbitmq" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
      {{- include "common.labels.standard" . | nindent 4 }}
data:
  rabbitmq-password: {{ required "notifier.rabbitmq.password is required" .Values.rabbitmq.auth.password }}
{{- end -}}
