# Sample configuration for a kubernetes cluster that has
# - Cert Manager with a ClusterIssuer called "letsencrypt"
# - ingress-nginx installed
global:
  ingress:
    enabled: true
    # Keycloak will be deployed automatically at: auth.osie.mycompany.com
    # You can change keycloak domain by setting: "keycloak.ingress.hostname"
    hostname: "osie.mycompany.com"
    ingressClassName: "nginx"
    annotations:
      # kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
      # Required by Keycloak when using Nginx ingress
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    secrets: []
    tls: true